---
version: "2.0"

services:
  web:
    image: registry.gitlab.com/blurt/blurt/condenser:dev
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
  blurt:
    image: faddat/blurtrpc-amd64
    expose:
      - port: 8090
        as: 8090
        to:
          - global: true
      - port: 8091
        as: 8091
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 1024Mi
        storage:
          size: 1024Mi
    blurt:
      resources:
        cpu:
          units: 1
        memory:
          size: 1024Mi
        storage:
          size: 60Gi
  placement:
    westcoast:
      pricing:
        web:
          denom: uakt
          amount: 1000

deployment:
  web:
    westcoast:
      profile: web
      count: 1
  blurt:
    westcoast:
      profile: blurt
      count: 4
